### ISSUE TITLE
メモ作成画面の実装(モック)

### ISSUE THREAD

**Issue by ngys-yt** [Progaku-copy/progaku-archive-front#40]
<img width="642" alt="スクリーンショット 2024-09-18 22 28 10" src="https://github.com/user-attachments/assets/a29d08e1-9f9e-4e25-b923-07a861135ae5">

**Comment by conte0745** [comment]
質問で
- タグ作成・編集画面と違って、画面タイトルは不要で良いすか？
- タグはメモと１対１対応ってことで大丈夫です？
